spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: rootpw
    driver-class-name: org.mysqlcj..jdbc.Driver
mybatis:
  type-aliases-package: com.example.myproject.mapper
  mapper-locations: mybatis/mapper/**/*.xml