spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: rootpw
    driver-class-name: org.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.example.login.mapper
  mapper-locations: mybatis/mapper/**/*.xml
  
  