spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: 11111111
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.example.webservice.mapper
  mapper-locations: mybatis/mapper/**/*.xml